# ----------------------------
# Makefile Options
# ----------------------------

NAME = WOLF3D
ICON = icon.png
DESCRIPTION = "wolfensteinCE by cocoa (@hotcocoaNcode gh)"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
