# ----------------------------
# Makefile Options
# ----------------------------

NAME = PONK
ICON = ponglogo.png
DESCRIPTION = "pong by cocoa (@hotcocoaNcode gh)"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
